=== diegoalonsom-07/lenguaje-marcas-1-mulweb/Segundaeva/XML/Practica_2/Practica_2_4/Practica_2_4.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PERFIL (PERSONA, DIRECCION, COD_POSTAL)>
<!ELEMENT PERSONA (NOMBRE_COM, APODO)+>
<!ELEMENT NOMBRE_COM (#PCDATA)>
<!ELEMENT APODO (#PCDATA)>
<!ELEMENT DIRECCION (CALLE, CIUDAD, PAIS)>
<!ELEMENT CALLE (#PCDATA)>
<!ELEMENT CIUDAD (#PCDATA)>
<!ELEMENT PAIS (#PCDATA)>
<!ELEMENT COD_POSTAL (#PCDATA)>

=== diegoalonsom-07/lenguaje-marcas-1-mulweb/Segundaeva/XML/Practica_2/Practica_2_4/Practica_2_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PERFIL SYSTEM "Practica_2_4.dtd">
<PERFIL>
    <PERSONA>
        <NOMBRE_COM></NOMBRE_COM>
        <APODO></APODO>
    </PERSONA>
    <DIRECCION>
        <CALLE></CALLE>
        <CIUDAD></CIUDAD>
        <PAIS></PAIS>
    </DIRECCION>
    <COD_POSTAL></COD_POSTAL>
</PERFIL>
