=== diegoalonsom-07/lenguaje-marcas-1-mulweb/Segundaeva/XML/Practica_2/Practica_2_2/Practica_2_2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT libro (titulo, autores, publicacion, editorial, isbn, fecha_compra)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT publicacion (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT fecha_compra (dia, mes, año)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== diegoalonsom-07/lenguaje-marcas-1-mulweb/Segundaeva/XML/Practica_2/Practica_2_2/Practica_2_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro SYSTEM "Practica_2_2.dtd">
<libro>
    <titulo>Arde París</titulo>
    <autores>
        <autor>
            <nombre>Dominique</nombre>
            <apellidos>Lapierre</apellidos>
        </autor>
        <autor>
            <nombre>Larry</nombre>
            <apellidos>Collins</apellidos>
        </autor>
    </autores>
    <publicacion>1975</publicacion>
    <editorial>Alfaguara</editorial>
    <isbn>97884010101</isbn>
    <fecha_compra>
        <dia>12</dia>
        <mes>10</mes>
        <año>2012</año>
    </fecha_compra>
</libro>
